### ISSUE TITLE
Feature Road Map

### ISSUE THREAD

**Issue by yashashri2102** [yashashri2102/mutual-fund-data-pipeline#1]
- [x] Write Dataflow to push data to bigquery 
- [x] If inclusive_start_date is sent to the dataflow, then a full load of data should be done
- [x] If not then, incremental data for a single day i.e. 1 day back data should be imported
- [ ] Giving UI ability to load full data as well as the incremental data
- [ ] To handle failures and loss of data, maintain a flag with a timestamp of the last successful run so that if anything goes wrong then job will import data of failure days and the 1 day back data together.
- [ ] Write SQL queries to fetch data for a specific mutual fund/ group of the mutual fund.
- [ ] Giving UI ability to filter based on mutual fund
- [ ] Creating container once the full-fledged application is ready
